version: 1.2
workflows:
 - name: scsorter_markerprediction
   subclass: WDL
   publish: true
   primaryDescriptorPath: /tasks/scsorter_run.wdl
   testParameterFiles:
    - /input_jsons/scsorter_run_inputs.json
   authors: 
    - orcid: 0000-0002-1385-2056 

 - name: Seurat_multisample
   subclass: WDL
   publish: true
   primaryDescriptorPath: /tasks/multisample_seurat.wdl
   testParameterFiles:
    - /input_jsons/multisample_seurat_inputs.json
   authors: 
    - orcid: 0000-0002-1385-2056 

 - name: linear_chain_single_sample_seurat_doubletsadd
   subclass: WDL
   publish: true
   primaryDescriptorPath: /tasks/linear_chain_adddoublets_seurat.wdl
   testParameterFiles: 
    - /input_jsons/linear_chain_adddoublets_seurat_inputs.json
   authors: 
    - orcid: 0000-0002-1385-2056 

 - name: singleR_immune_nonimmune
   subclass: WDL
   publish: true
   primaryDescriptorPath: /tasks/singleR_immune_nonimmune_pipeline.wdl
   testParameterFiles: 
    - /input_jsons/singleR_immune_nonimmune_pipeline_inputs.json
   authors: 
    - orcid: 0000-0002-1385-2056 

 - name: QC_plots
   subclass: WDL
   publish: true
   primaryDescriptorPath: /tasks/plot_qc.wdl
   testParameterFiles: 
    - /input_jsons/plot_qc_inputs.json
   authors: 
    - orcid: 0000-0002-1385-2056 

 - name: singleR_singleref
   subclass: WDL
   publish: true
   primaryDescriptorPath: /tasks/SingleR_singleref.wdl
   testParameterFiles: 
    - /input_jsons/SingleR_singleref_inputs.json
   authors: 
    - orcid: 0000-0002-1385-2056 

 - name: Add_doublet_info
   subclass: WDL
   publish: true
   primaryDescriptorPath: /tasks/add_doubletinfo.wdl
   testParameterFiles: 
    - /input_jsons/add_doubletinfo_inputs.json
   authors: 
    - orcid: 0000-0002-1385-2056 

 - name: Seurat_clustering_simple
   subclass: WDL
   publish: true
   primaryDescriptorPath: /tasks/clustering_n_pca_simple.wdl
   testParameterFiles: 
    - /input_jsons/clustering_n_pca_simple_inputs.json
   authors: 
    - orcid: 0000-0002-1385-2056 

 - name: Seurat_rPCA_integration
   subclass: WDL
   publish: true
   primaryDescriptorPath: /tasks/rpca_integration.wdl
   testParameterFiles: 
    - /input_jsons/rpca_integration_inputs.json
   authors: 
    - orcid: 0000-0002-1385-2056 

 - name: Add_cellid_to_srt
   subclass: WDL
   publish: true
   primaryDescriptorPath: /tasks/add_cellid_results_to_seurat.wdl
   testParameterFiles: 
    - /input_jsons/add_cellid_results_to_seurat_inputs.json
   authors: 
    - orcid: 0000-0002-1385-2056 

 - name: Doublet_colletion
   subclass: WDL
   publish: true
   primaryDescriptorPath: /tasks/Doublet_calling.wdl
   testParameterFiles: 
    - /input_jsons/Doublet_calling_inputs.json
   authors: 
    - orcid: 0000-0002-1385-2056 

 - name: Featureplot_genes
   subclass: WDL
   publish: true
   primaryDescriptorPath: /tasks/make_gene_featplots.wdl
   testParameterFiles: 
    - /input_jsons/make_gene_featplots_inputs.json
   authors: 
    - orcid: 0000-0002-1385-2056 
 
 - name: subset_renormalize_recluster
   subclass: WDL
   publish: true
   primaryDescriptorPath: /tasks/subset_renormalize_recluster.wdl
   testParameterFiles:
    -  /input_jsons/subset_renormalize_recluster_inputs.json
   authors: 
    - orcid: 0000-0002-1385-2056 

 - name: recluster_renormalize
   subclass: WDL
   publish: true
   primaryDescriptorPath: /subworkflows/recluster_renorm_rerun_singleR.wdl
   testParameterFiles: 
    - /input_jsons/recluster_renorm_rerun_singleR_inputs.json
   authors: 
    - orcid: 0000-0002-1385-2056 

 - name: scatter_gather_singleR
   subclass: WDL
   publish: true
   primaryDescriptorPath: /subworkflows/scatter_gather_singleR.wdl
   testParameterFiles: 
    -  /input_jsons/scatter_gather_singleR_inputs.json
   authors: 
    - orcid: 0000-0002-1385-2056 

 - name: filter_n_doublets
   subclass: WDL
   publish: true
   primaryDescriptorPath: /subworkflows/single_sample_filtering_nd_doublets.wdl
   testParameterFiles:
    - /input_jsons/single_sample_filtering_nd_doublets_inputs.json
   authors: 
    - orcid: 0000-0002-1385-2056 

 - name: scatter_htmap
   subclass: WDL
   publish: true
   primaryDescriptorPath: /subworkflows/scatter_deg.wdl
   testParameterFiles: 
    - /input_jsons/scatter_deg_inputs.json
   authors: 
    - orcid: 0000-0002-1385-2056 

 - name: scatter_doublet
   subclass: WDL
   publish: true
   primaryDescriptorPath: /subworkflows/scatter_gather_Doubletcall_multisample.wdl
   testParameterFiles: 
    - /input_jsons/scatter_gather_Doubletcall_multisample_inputs.json
   authors: 
    - orcid: 0000-0002-1385-2056 

 - name: seurat_counts_to_anndata
   subclass: WDL
   publish: true
   primaryDescriptorPath: /subworkflows/seurat_counts_to_anndata.wdl
   testParameterFiles: 
    - /input_jsons/seurat_counts_to_anndata_inputs.json
   authors: 
    - orcid: 0000-0002-1385-2056 

 - name: scatter_gather_scsorter
   subclass: WDL
   publish: true
   primaryDescriptorPath: /subworkflows/scatter_gather_scsorter.wdl
   testParameterFiles: 
    - /input_jsons/scatter_gather_scsorter_inputs.json
   authors: 
    - orcid: 0000-0002-1385-2056 

 - name: filter_n_cluster
   subclass: WDL
   publish: true
   primaryDescriptorPath: /subworkflows/single_sample_filtering_n_clustering.wdl
   testParameterFiles: 
    - /input_jsons/single_sample_filtering_n_clustering_inputs.json
   authors: 
    - orcid: 0000-0002-1385-2056 

 - name: scatter_doublet
   subclass: WDL
   publish: true
   primaryDescriptorPath: /subworkflows/scatter_gather_doublet_singlesample.wdl
   testParameterFiles: 
    - /input_jsons/scatter_gather_doublet_singlesample_inputs.json
   authors: 
    - orcid: 0000-0002-1385-2056 

 - name: run_singleR_by_sample
   subclass: WDL
   publish: true
   primaryDescriptorPath: /subworkflows/scatter_gather_singleR_bysample.wdl
   testParameterFiles: 
    - /input_jsons/scatter_gather_singleR_bysample_inputs.json
   authors: 
    - orcid: 0000-0002-1385-2056 

 - name: scatter_rpca
   subclass: WDL
   publish: true
   primaryDescriptorPath: /subworkflows/scatter_rpca.wdl
   testParameterFiles: 
    - /input_jsons/scatter_rpca_inputs.json
   authors: 
    - orcid: 0000-0002-1385-2056 

 - name: multisample_seurat_doublet_singler
   subclass: WDL
   publish: true
   primaryDescriptorPath: /pipelines/multisample_seurat_doublet_singler.wdl
   testParameterFiles: 
    - /input_jsons/multisample_seurat_doublet_singler_inputs.json
   authors: 
    - orcid: 0000-0002-1385-2056 

 - name: end_to_end_seurat_single_sample
   subclass: WDL
   publish: true
   primaryDescriptorPath: /pipelines/end_to_end_seurat_singlesample.wdl
   testParameterFiles: 
    - /input_jsons/end_to_end_seurat_singlesample_inputs.json
   authors: 
    - orcid: 0000-0002-1385-2056 

 - name: end_to_end_seurat_multi_sample
   subclass: WDL
   publish: true
   primaryDescriptorPath: /pipelines/end_to_end_multisample.wdl
   testParameterFiles:
    - /input_jsons/end_to_end_multisample_inputs.json
   authors: 
    - orcid: 0000-0002-1385-2056 

 - name: end_to_end_seurat_single_sample
   subclass: WDL
   publish: true
   primaryDescriptorPath: /pipelines/seurat_single_sample_nomerging.wdl
   testParameterFiles: 
    - /input_jsons/seurat_single_sample_nomerging_inputs.json
   authors: 
    - orcid: 0000-0002-1385-2056

 - name : Seurat_single_sample
   subclass: WDL
   publish: true
   primaryDescriptorPath: /tasks/single_sample_seurat.wdl
   testParameterFiles:
    - /input_jsons/single_sample_seurat_inputs.json
   authors:
    - orcid: 0000-0002-1385-2056 
